[package]
name = "mouse-move-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouse-rs = "0.4"
rand = "0.8.5"
crossbeam-channel = "0.5.8"
anyhow = "1.0.72"
ctrlc = "3.4.0"
